version: '3.4'

services:
  backend:
    image: backend
    container_name: vizi_backend
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - /app/node_modules
    expose:
      - '8080'
    restart: on-failure
    ports:
      - 8080:8080
