import {
  getCompanyProjectsService,
  getProjectByIdService,
  createProjectService,
  addApartmentService,
  addPanoramaService,
  addHotspotService,
  addMarkerService,
  deleteProjectService,
  deletePanoramaService,
  deleteMarkerService,
  deleteHotspotService,
  deleteApartmentService,
  editProjectService,
  getPanoramaByIdService,
  editHotspotService,
  editProfileService,
} from './company.service';

export {
  getProjectByIdService,
  createProjectService,
  addApartmentService,
  addPanoramaService,
  addMarkerService,
  addHotspotService,
  deleteProjectService,
  deletePanoramaService,
  deleteMarkerService,
  deleteHotspotService,
  deleteApartmentService,
  getCompanyProjectsService,
  editProjectService,
  getPanoramaByIdService,
  editHotspotService,
  editProfileService,
};
